<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

namespace GPBMetadata;

class Greeter
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a500a0d677265657465722e70726f746f22370a054576656e74120a0a02" .
            "696418012001280912110a0974696d657374616d70180220012803120f0a" .
            "076d657373616765180320012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

